---
# tasks file for nginx

 - name: install nginx
   apt: name={{item}} state=present update_cache=yes
   with_items:
      - nginx
      - python-httplib2

 - name: ensure nginx is started
   service: name=nginx state=started
