---
# tasks file for apache2

 - name: installing apache websserver
   apt: name={{item}} state=present update_cache=yes
   with_items:
     - apache2

 - name: ensure apache is started
   service: name=apache2 state=started
