---
# tasks file for loadbalanceri

 - name: configure LB nginx
   template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ item.key }} mode=0644
   with_dict: "{{ sites }}"
   notify: restart nginx

 - name: get list of non active sites 
   shell: ls /etc/nginx/sites-enabled
   register: listofallsites

 - name: de-activate  nginx site
   file: path=/etc/nginx/sites-enabled/{{item}} state=absent
   #debug: msg="-------- {{item}} --------"
   with_items: "{{ listofallsites.stdout_lines }}"
   when: item  not in  sites
   notify: restart nginx

 - name: activate LB
   file: src=/etc/nginx/sites-available/{{ item.key }}  dest=/etc/nginx/sites-enabled/{{ item.key }}  state=link
   with_dict: "{{ sites }}"
   notify: restart nginx
